-- Create survey_submissions table
CREATE TABLE IF NOT EXISTS survey_submissions (
    id SERIAL PRIMARY KEY,
    amenitiesSatisfaction INTEGER,
    amenitiesImprovements TEXT,
    amenitiesUsage TEXT[],
    securitySatisfaction INTEGER,
    securityConcerns TEXT,
    securityImprovements TEXT[],
    conciergeRating INTEGER,
    conciergeImprovements TEXT[],
    maintenanceSatisfaction INTEGER,
    maintenanceIssues TEXT,
    maintenanceResponseSatisfaction INTEGER,
    maintenanceCommonIssues TEXT[],
    maintenancePriorityAreas TEXT[],
    communityInterest TEXT,
    communitySuggestions TEXT,
    communityImportance INTEGER,
    financialSatisfaction INTEGER,
    financialTransparency INTEGER,
    financialConcerns TEXT[],
    financialPriorities TEXT,
    financialReportsFrequency TEXT,
    communicationSatisfaction INTEGER,
    communicationPreferredMethod TEXT,
    communicationFrequency TEXT,
    communicationSuggestions TEXT,
    projectsAwareness TEXT,
    projectsSatisfaction INTEGER,
    projectsConcerns TEXT[],
    projectsSuggestions TEXT,
    residentDuration TEXT,
    residentStatus TEXT,
    topPriorities TEXT,
    additionalComments TEXT,
    contactName TEXT,
    contactEmail TEXT,
    contactUnit TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    building TEXT DEFAULT '95 Prince Arthur Ave'
); 